CREATE TABLE BIN_TILES AS
  SELECT ID, GEOMETRY
  FROM TABLE(SDO_SAM.TILED_BINS(-180,180,-90,90,5,8307));

ALTER TABLE us_cities ADD (bin_id number);

exec SDO_SAM.BIN_LAYER('US_CITIES','LOCATION','BIN_TILES','GEOMETRY','BIN_ID');
